version: '2'

services:
  jupyterhub:
    build: jupyterhub
    container_name: jupyterhub_hub
    image: digitalalloys/jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
    expose:
      - "8000"
    networks:
      - webgateway
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.port=8000"
      - "traefik.frontend.rule=Host:jupyter.digitalalloys.com"
      - "traefik.docker.network=webgateway"
    restart: on-failure

  jupyterlab:
    build: jupyterlab
    image: digitalalloys/jupyterlab

networks:
  webgateway:
    external:
      name: webgateway

volumes:
  jupyterhub_data:
